
### Site metadata

# Don't make the title longer than this, otherwise it gets covered in mobile view.

title: Chingam Fong's homepage
description: A page for my project and potentially interesting things about me

email: fongchingam@link.cuhk.edu.hk
github_username: fongchingam
rss: RSS

### Build settings
theme: minima

navigation: main




